### ISSUE TITLE
Autocompletion not working in .bashrc file

### ISSUE THREAD

**Issue by jrmd54** [josa42/coc-sh#73] opened 2023-08-03 10:55 UTC
Hello,

I noticed that coc-sh autocompletion was not working with my .bashrc file.
After doing some tests it seems that removing the following lines (that are present by default in the .bashrc file of my Ubuntu distribution) makes the file parsable by coc-sh, but doing so remove the title from the terminal.

```
# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac
```

Shouldn't these lines be normally parsed by coc-sh?

**Comment by josa42** [comment] 2023-10-24 05:47
> Shouldn't these lines be normally parsed by coc-sh?

coc-sh does not parse anything, that is done by [bash-language-server](https://github.com/bash-lsp/bash-language-server).

Closing the issue, because I cannot reproduce it.

**Closed by josa42** 2023-10-24 05:47 UTC
